# 01 · Extraer consumos extremos respecto de la mediana de cada mercado

Práctica basada en `notebooks/02_energia.ipynb`. Tiempo sugerido: 20–30 minutos.

**Tu tarea:** completá únicamente la función de la sección 3.
La carga de datos, el entorno y las pruebas ya están preparados.

1. Elegí el kernel del entorno `.venv` del proyecto y ejecutá las celdas de preparación.
2. Leé el contrato y reemplazá el `raise NotImplementedError` por tu implementación.
3. Ejecutá de nuevo la celda de la función y después la de pruebas.
4. Si todas pasan, esa misma celda probará tu función sobre los datos reales y mostrará el resultado.

Podés usar **Ejecutar todo** desde un kernel nuevo. Mientras la función esté pendiente,
la última celda mostrará un aviso; no tenés que instalar nada adicional en el entorno actual.

## 1. Preparación lista

En esta práctica se usa el equivalente a `df`: filas con ambas mediciones presentes.

Los archivos de `../datos/` ya están descargados. Si faltan, se descargan una vez desde Kaggle y se guardan localmente.

In [50]:
from pathlib import Path
import sys

import numpy as np
import pandas as pd
from IPython.display import display
from pandas.testing import assert_frame_equal

# Encuentra la carpeta tanto desde la raíz del proyecto como desde este notebook.
ubicaciones = [Path.cwd(), *Path.cwd().parents]
carpeta = next(
    (
        candidata
        for ubicacion in ubicaciones
        for candidata in [ubicacion, ubicacion / "practicas_livecoding"]
        if candidata.name == "practicas_livecoding"
        and (candidata / "preparacion.py").is_file()
    ),
    None,
)
if carpeta is None:
    raise FileNotFoundError("Abrí el notebook dentro de la carpeta practicas_livecoding.")

if str(carpeta) not in sys.path:
    sys.path.insert(0, str(carpeta))

from preparacion import cargar_viviendas, cargar_energia

pd.set_option("display.max_columns", 20)

In [51]:
datos = cargar_energia()
datos = datos.dropna(subset=["Consumo", "Consumidores"]).copy()

print(f"Filas: {len(datos):,} | Columnas: {len(datos.columns)}")
display(datos.head())

Filas: 271,811 | Columnas: 13

,TipoConsumidor,Sistema,UF,Classe,Setor Econômico - N2,Setor Econômico - N3,Tipo Tensão - N1,Tipo Tensão - N2,Tipo Tensão - N3,Faixa de Consumo N1,Faixa de Consumo N2,Consumidores,Consumo
Data,,,,,,,,,,,,,
2014-01-01,Cativo,Sudeste / Centro-Oeste,RO,Residencial,Convencional (Excepto Baixa Renda),TOTAL,A - Alta Tensão,TOTAL,TOTAL,Alta Tensão,Alta Tensão,1.0,8.0
2014-01-01,Cativo,Sudeste / Centro-Oeste,SP,Rural,Serviço Público de Irrigação,TOTAL,A - Alta Tensão,"A-4 - 2,3 a 25 kV",TOTAL,Não Aplicável,Não Aplicável,6.0,145.0
2014-01-01,Cativo,Sudeste / Centro-Oeste,SP,Rural,Serviço Público de Irrigação,TOTAL,B - Baixa Tensão,TOTAL,TOTAL,Não Aplicável,Não Aplicável,31.0,18.0
2014-01-01,Cativo,Sudeste / Centro-Oeste,MS,Residencial,Baixa Renda,Baixa Renda N2,B - Baixa Tensão,TOTAL,TOTAL,Baixa Renda,> 200 kWh,44193.0,13171.0
2014-01-01,Cativo,Sistemas Isolados,AC,Residencial,Convencional (Excepto Baixa Renda),TOTAL,B - Baixa Tensão,TOTAL,TOTAL,Convencional,0-30 kWh,5216.0,149.0

## 2. Consigna y resultado esperado

Aplicá el ejercicio de las medianas al dataset de energía: por cada `TipoConsumidor`,
calculá la mediana de `Consumo` y extraé las `n` filas más alejadas en valor absoluto.

- La entrada ya contiene las filas con `Consumo` y `Consumidores` presentes.
  Conservá los consumos negativos y los ceros para este cálculo.
- Devolvé todas las columnas originales, seguidas por `mediana_grupo` y `distancia_mediana`.
- Ordená los mercados alfabéticamente y las distancias de mayor a menor en cada mercado.
  Los empates deben conservar el orden original de las filas.
- Conservá el índice `Data`, aunque esté repetido: distintas filas del mismo mes son válidas.
- `n` es positivo; los grupos menores que `n` aportan todas sus filas.
  Una entrada vacía devuelve una tabla vacía con las columnas esperadas.
- No modifiques la entrada ni elimines duplicados por fecha.

## 3. Tu función

Editá solo esta celda. Mantené el nombre de la función y sus parámetros para que funcionen las pruebas.

In [57]:
def extraer_extremos_por_mercado(datos, n=5):
    """Implementá el contrato de la sección 2 sin modificar datos."""
    # TODO: escribí tu solución acá.
    resultado=datos.copy()
    resultado["grupo_medianas"]=resultado.groupby("TipoConsumidor")["Consumo"].transform("median")
    resultado["distancia_mediana"]=(resultado["Consumo"]-resultado["grupo_medianas"]).abs()
    ordenado=resultado.sort_values("distancia_mediana", ascending=False,kind="stable")
    extremos=ordenado.groupby("TipoConsumidor",sort=False).head(n)
    display(ordenado.head(10))
    display (extremos)

    #raise NotImplementedError("Completá esta función y volvé a ejecutar las pruebas.")

In [58]:
extraer_extremos_por_mercado(datos,n=5)

,TipoConsumidor,Sistema,UF,Classe,Setor Econômico - N2,Setor Econômico - N3,Tipo Tensão - N1,Tipo Tensão - N2,Tipo Tensão - N3,Faixa de Consumo N1,Faixa de Consumo N2,Consumidores,Consumo,grupo_medianas,distancia_mediana
Data,,,,,,,,,,,,,,,
2022-04-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,410.000,1850736.195,6017.614,1844718.581
2022-05-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,413.000,1815405.730,6017.614,1809388.116
2022-08-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,417.000,1813350.475,6017.614,1807332.861
2022-09-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,420.000,1805476.071,6017.614,1799458.457
2021-04-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,397.806,1801521.125,6017.614,1795503.511
2021-11-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,401.459,1795922.080,6017.614,1789904.466
2022-03-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,410.000,1781314.577,6017.614,1775296.963
2023-11-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,391.000,1780565.056,6017.614,1774547.442
2021-01-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,400.702,1777157.052,6017.614,1771139.438
2021-10-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,401.768,1775669.169,6017.614,1769651.555

,TipoConsumidor,Sistema,UF,Classe,Setor Econômico - N2,Setor Econômico - N3,Tipo Tensão - N1,Tipo Tensão - N2,Tipo Tensão - N3,Faixa de Consumo N1,Faixa de Consumo N2,Consumidores,Consumo,grupo_medianas,distancia_mediana
Data,,,,,,,,,,,,,,,
2022-04-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,410.000,1850736.195,6017.614,1844718.581
2022-05-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,413.000,1815405.730,6017.614,1809388.116
2022-08-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,417.000,1813350.475,6017.614,1807332.861
2022-09-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,420.000,1805476.071,6017.614,1799458.457
2021-04-01,Livre,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,397.806,1801521.125,6017.614,1795503.511
2014-11-01,Cativo,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,"A-4 - 2,3 a 25 kV",TOTAL,Não Aplicável,Não Aplicável,16723.000,1395433.000,1159.000,1394274.000
2014-10-01,Cativo,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,"A-4 - 2,3 a 25 kV",TOTAL,Não Aplicável,Não Aplicável,16725.000,1387076.000,1159.000,1385917.000
2014-02-01,Cativo,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,"A-4 - 2,3 a 25 kV",TOTAL,Não Aplicável,Não Aplicável,16756.000,1386881.000,1159.000,1385722.000
2014-03-01,Cativo,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,"A-4 - 2,3 a 25 kV",TOTAL,Não Aplicável,Não Aplicável,16746.000,1356867.000,1159.000,1355708.000
2014-09-01,Cativo,Sudeste / Centro-Oeste,SP,Industrial,TOTAL,TOTAL,A - Alta Tensão,"A-4 - 2,3 a 25 kV",TOTAL,Não Aplicável,Não Aplicável,16724.000,1347298.000,1159.000,1346139.000

## 4. Pruebas y ejecución real

Un `AssertionError` indica qué resultado difiere del esperado. Primero revisá el caso pequeño que falló. Después de editar la función, ejecutá su celda antes de volver a correr estas pruebas.

Las pruebas verifican ejemplos pequeños y propiedades del resultado real; no sustituyen una revisión de tu razonamiento.

In [54]:
# Estas pruebas no reemplazan tu función: comprueban su resultado.
def comparar(actual, esperado):
    assert isinstance(actual, pd.DataFrame), "La función debe devolver un DataFrame."
    assert_frame_equal(
        actual, esperado,
        check_dtype=False, check_index_type=False, check_column_type=False,
        check_freq=False, rtol=1e-6, atol=1e-8,
    )


def probar(funcion):
    caso = pd.DataFrame({
        "TipoConsumidor": ["B", "A", "A", "B", "A", "C", "B"],
        "Consumo": [10, 100, -20, 20, 40, 7, 30],
        "identificador": list("abcdefg"),
    }, index=pd.DatetimeIndex(["2023-01-01"] * 3 + ["2023-02-01"] * 4, name="Data"))
    original = caso.copy(deep=True)

    # Empates, grupos con menos de n filas y conservación de las columnas originales.
    esperado = caso.iloc[[1, 2, 0, 6, 5]].copy()
    esperado["mediana_grupo"] = [40, 40, 20, 20, 7]
    esperado["distancia_mediana"] = [60, 60, 10, 10, 0]
    comparar(funcion(caso, n=2), esperado)
    comparar(caso, original)

    comparar(funcion(caso, n=1), esperado.iloc[[0, 2, 4]])

    esperado_todos = caso.iloc[[1, 2, 4, 0, 6, 3, 5]].copy()
    esperado_todos["mediana_grupo"] = [40, 40, 40, 20, 20, 20, 7]
    esperado_todos["distancia_mediana"] = [60, 60, 0, 10, 10, 0, 0]
    comparar(funcion(caso, n=99), esperado_todos)

    vacio = caso.iloc[:0].copy()
    esperado_vacio = vacio.copy()
    esperado_vacio["mediana_grupo"] = pd.Series(dtype=float)
    esperado_vacio["distancia_mediana"] = pd.Series(dtype=float)
    comparar(funcion(vacio, n=5), esperado_vacio)
    comparar(caso, original)
    print("OK: extremos, empates, n variable, grupo pequeño, entrada vacía y datos intactos.")


resultado = None
try:
    probar(extraer_extremos_por_mercado)
except NotImplementedError:
    print("PENDIENTE: completá la función de la sección 3 y volvé a ejecutar esta celda.")
else:
    # Comprobamos también que el dataset real permanezca intacto.
    antes = datos.copy(deep=True)
    resultado = extraer_extremos_por_mercado(datos)
    comparar(datos, antes)
    assert list(resultado.columns) == list(datos.columns) + ["mediana_grupo", "distancia_mediana"]
    assert len(resultado) == datos.groupby("TipoConsumidor").size().clip(upper=5).sum()
    for grupo, filas in resultado.groupby("TipoConsumidor"):
        valores = datos.loc[datos["TipoConsumidor"] == grupo, "Consumo"]
        distancias = np.sort(np.abs(valores.to_numpy() - np.median(valores)))[::-1][:5]
        np.testing.assert_allclose(filas["distancia_mediana"], distancias)
        np.testing.assert_allclose(filas["mediana_grupo"], np.median(valores))
    print(f"OK: dataset real. Resultado: {len(resultado):,} filas.")
    display(resultado.head(20))

,TipoConsumidor,Consumo,identificador,grupo_medianas,distancia_mediana
Data,,,,,
2023-01-01,A,100,b,40.0,60.0
2023-01-01,A,-20,c,40.0,60.0
2023-01-01,B,10,a,20.0,10.0
2023-02-01,B,30,g,20.0,10.0
2023-02-01,B,20,d,20.0,0.0
2023-02-01,A,40,e,40.0,0.0
2023-02-01,C,7,f,7.0,0.0

AssertionError: La función debe devolver un DataFrame.

## Pista opcional

<details>
<summary>Abrir solo si te trabás</summary>

Usá una mediana por grupo alineada con las filas. Un índice temporal repetido no identifica una fila única.

</details>

**Para explicar en voz alta:** ¿qué filas entran al cálculo?, ¿qué representa cada fila de la salida?, ¿qué caso límite cubre cada prueba?

In [ ]:
display(datos)

,TipoConsumidor,Sistema,UF,Classe,Setor Econômico - N2,Setor Econômico - N3,Tipo Tensão - N1,Tipo Tensão - N2,Tipo Tensão - N3,Faixa de Consumo N1,Faixa de Consumo N2,Consumidores,Consumo
Data,,,,,,,,,,,,,
2014-01-01,Cativo,Sudeste / Centro-Oeste,RO,Residencial,Convencional (Excepto Baixa Renda),TOTAL,A - Alta Tensão,TOTAL,TOTAL,Alta Tensão,Alta Tensão,1.0,8.000
2014-01-01,Cativo,Sudeste / Centro-Oeste,SP,Rural,Serviço Público de Irrigação,TOTAL,A - Alta Tensão,"A-4 - 2,3 a 25 kV",TOTAL,Não Aplicável,Não Aplicável,6.0,145.000
2014-01-01,Cativo,Sudeste / Centro-Oeste,SP,Rural,Serviço Público de Irrigação,TOTAL,B - Baixa Tensão,TOTAL,TOTAL,Não Aplicável,Não Aplicável,31.0,18.000
2014-01-01,Cativo,Sudeste / Centro-Oeste,MS,Residencial,Baixa Renda,Baixa Renda N2,B - Baixa Tensão,TOTAL,TOTAL,Baixa Renda,> 200 kWh,44193.0,13171.000
2014-01-01,Cativo,Sistemas Isolados,AC,Residencial,Convencional (Excepto Baixa Renda),TOTAL,B - Baixa Tensão,TOTAL,TOTAL,Convencional,0-30 kWh,5216.0,149.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-01,Cativo,Sistemas Isolados,AP,Rural,Rural Residencial,TOTAL,B - Baixa Tensão,TOTAL,TOTAL,Não Aplicável,Não Aplicável,11.0,4.406
2023-12-01,Cativo,Sudeste / Centro-Oeste,SP,Comercial,Outros Serviços e Atividades,TOTAL,A - Alta Tensão,A-2 - 88 a 138 kV,TOTAL,Não Aplicável,Não Aplicável,2.0,227.320
2023-12-01,Cativo,Sudeste / Centro-Oeste,SP,Comercial,Outros Serviços e Atividades,TOTAL,B - Baixa Tensão,TOTAL,TOTAL,Não Aplicável,Não Aplicável,181517.0,75490.903
2023-12-01,Cativo,Sistemas Isolados,AP,Poder Público,Federal,TOTAL,B - Baixa Tensão,TOTAL,TOTAL,Não Aplicável,Não Aplicável,36.0,74.694
2023-12-01,Cativo,Sudeste / Centro-Oeste,MS,Residencial,Baixa Renda,Baixa Renda Indígena,B - Baixa Tensão,TOTAL,TOTAL,Baixa Renda,0-30 kWh,830.0,24.709